---
output: html_document
---

<div align="center">
  <h1>NIH-R01 Advanced Spatial Transcriptomics Analysis</h1>
</div>
<br>

<div align="center">
  <h1>🚧 Under Construction 🚧</h1>
  <p>We are building our website... Please check back soon for updates. Thank you for your patience!</p>
</div>

<br>



<h3 style="font-weight: bold;">Brief project overview</h3>

This proposal focuses on addressing analytical challenges in complex spatial transcriptomics (ST) data, particularly in the context of malignant human diseases like gliomas and melanoma brain metastasis. Recent advancements in single-cell genome sequencing allow for detailed gene expression profiling at the individual cell level, offering insights that conventional bulk analyses miss. The proposal aims to develop innovative analytical methods to enhance understanding of cellular heterogeneity and identify significant biomarkers associated with various brain tumors.
<br>
<br>

<h3 style="font-weight: bold;">Key objectives</h3>

 - Improving cell clustering accuracy using spatial information
 - Developing transfer learning methods for better cell analysis
 - Creating statistical tools to assess gene importance in cell structures
<br>
<br>

<h3 style="font-weight: bold;">Impact on brain tumor research</h3>
🚧 Website Under Construction… 🚧
<br>
<br>

<h3 style="font-weight: bold;">Quick links to key resources</h3>
🚧 Website Under Construction… 🚧
<br>
<br>

<h3 style="font-weight: bold;">Contacts</h3>

Please send you feedback/comments/suggestions to us at [cbsr@cumc.columbia.edu](mailto:cbsr@cumc.columbia.edu).

<br>
<br>
<br>
<br>


---
`[^1]:`{=markdown} Developed by Hu Lab and Collaborators.

